### ISSUE TITLE
Grouping or merging identical dependencies

### ISSUE THREAD

**Issue by eoftedal** [stevespringett/dependency-track#113]
Currently if the same dependency (same name and version) exists multiple places in the dependency tree (transitively), then it's listed multiple times in the project, and vulnerability information is only provided for the first occurence of a the version.

Ideally if the same component is used mulitple times in the dependency, it should be listed only once (per version), and with vulnerability info.

**Comment by eoftedal** [comment]
Example:
```
{
  "name": "dep-track-test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "express": "^4.16.3"
  }
}
```
Express contains the same dependencies multiple times (example parseurl@1.3.2):
http://npm.anvaka.com/#/view/2d/express

This is the BOM (is this correct?):
[bom.xml.txt](https://github.com/stevespringett/dependency-track/files/1847912/bom.xml.txt)

**Comment by stevespringett** [comment]
After reviewing the bom, I don't think this is a defect.

Refer to the CycloneDX documentation at https://github.com/CycloneDX/specification/blob/master/schema/bom-1.0.xsd#L110

The optional child components should not represent a dependency-tree. Think of child components as you would for bill of materials. For example, the cigarette lighter is a component of the ashtray which is a component of the dashboard.

In the software world, multi-module builds like those that can be performed by Maven would also quality. For example:

* FasterXML Jackson v2.9.4
  * Jackson Databind v2.9.4
  * Jackson Core v2.9.4
  * Jackson Annotations v2.9.4

Since I do not believe npm supports this concept, it's highly unlikely that you would have nested components. For npm projects, I would expect a nearly flat tree, with at most one level deep of nesting.

In the case of the bom provided, it is saying that parseurl@1.3.2 is a subcomponent of multiple other components, which isn't the case. As a result, parseurl is being added multiple times because each instance of parseurl has a different parent component.
