### ISSUE TITLE
Number of component is incorrect

### ISSUE THREAD

**Issue by stboiss** [stevespringett/dependency-track#117]
in dashboard, number of component (total) and number of vulnerables componentis not good.
![screenshot 2018-03-29 10-58-05 001](https://user-images.githubusercontent.com/24654609/38080046-b50dafa8-3340-11e8-96d7-10317f5bf54d.png)
one component is counted for each project to which it is linked
in my database, I have 116 components (109 linked to first project and 111 to second) and 7 components are vulnerable.

**Comment by stevespringett** [comment]
This was the intended behavior and ideally the labels should read "Dependency" rather than component. But I think it's valuable to have both metrics.

The Total/Vulnerable Components as well as the Total/Vulnerable Dependencies.

I'm thinking they should both appear on the same graph. Any reason why they should be on separate graphs (adds to confusion perhaps)? Thoughts?

**Comment by stevespringett** [comment]
This issue is partially resolved in the trunk. Still need to modify graphs. Will be fully resolved in 3.1
