### ISSUE TITLE
Previous dependencies are not removed from project

### ISSUE THREAD

**Issue by eoftedal** [stevespringett/dependency-track#123]
I'm submitting dependency-check xml reports from a CI build for a multimodule project. 

As discussed on the OWASP slack, old dependencies are not removed, so each subproject is added once for each build (as their hash changes). Also for upgraded dependencies (jackson 2.9.4 -> 2.9.5), both versions exist in the project.

Expected behaviour:
Should remove old dependencies from project

Future requirement:
CI builds will create a lot of versions of the same component ( example-module 1.2.0) because CI will  submit a new version (new hash) every time.  These should either be grouped under the same component name / version, or it should be possible to set some kind of component/policy or per-component-policy (overwrite previous versions with same purl or similar).

**Comment by eoftedal** [comment]
Test case:
First import dependency-check-report-1.xml and then import dependency-check-report-2.xml into the same project. The project will now contain jackson-databind 2.9.4 and 2.9.5

[reports.zip](https://github.com/stevespringett/dependency-track/files/1874887/reports.zip)

**Comment by stevespringett** [comment]
Thanks @eoftedal. Although the milestone says 3.1, I'm going to push a fix to the 3.0 branch along with a minor release. Will start working on this in the next day or two.

**Comment by stevespringett** [comment]
When importing scans and boms, all components are reconciled. Components that are not included in the bom/scan are removed from being a dependency of the project, and components that are not already a dependency are added.

In the example case provided, jackson-databind 2.9.5 should have replaced 2.9.4 so that only one jackson-databind version is a dependency of the project. And both versions should have been listed in the main Components view.

Screenshot of 3.1 showing the issue being fixed (3.0.x is also fixed).

Result after uploading dependency-check-report-1.xml:
![import-1](https://user-images.githubusercontent.com/3878933/38715617-ded88bc0-3ea1-11e8-89c8-63560eb375b2.png)

Result after uploading dependency-check-report-2.xml:
![import-2](https://user-images.githubusercontent.com/3878933/38715623-e581e9f8-3ea1-11e8-8d93-19935c6a3aba.png)

Components view:
![components](https://user-images.githubusercontent.com/3878933/38715629-f01773d8-3ea1-11e8-8013-017f98fbebe1.png)

I plan on releasing 3.0.3 Friday or Saturday that resolves this issue.

**Comment by stevespringett** [comment]
This should be resolved in v3.0.3 released today.
