### ISSUE TITLE
Adding new vulnerabilities

### ISSUE THREAD

**Issue by CalldiDoctor** [stevespringett/dependency-track#21]
Since the dependency check look for vulnerabilities in the NVD, I think it could be interesting to be able to add vulnerabilities through another mechanism. 
I can figure out that adding another database to look for vulnerabilities there is not in the scope of this project, however, adding the possibility to add new vulnerabilities manually could be interesting.
What do you think about this idea, and which is, in your opinion, the best approach?

I would be interested in contributing to this new feature.

**Comment by stevespringett** [comment]
Dependency-Check supports alternatives to NVD. It is possible to add another data source so that they can be imported by DT.

I'm not sure how I feel about manually adding vulnerabilities in the UI, but I would be in favor of plugging DT into alternative sources via an API

What do you envision for manually adding vulnerabilities? How would this work and would there be specific types of vulnerabilities (by CWE for example) supported?

**Comment by stevespringett** [comment]
Support for Node Security Platform is already complete, and support for VulnDB is a work in progress. These two sources of data are in addition to the support for the NVD.

In addition, the Vulnerability object has a 'MANUAL' enum type that will be used (in the future) to manually add vulnerabilities.

**Comment by stevespringett** [comment]
A preview of this feature will be included in v3.0 and will likely be fully complete in v3.1.

![add-vulnerability-preview](https://user-images.githubusercontent.com/3878933/36462422-e71317a6-1688-11e8-95c9-183ce9d4511e.png)

**Comment by stevespringett** [comment]
This is a two-part enhancement. The adding of vulnerabilities is now complete and closes this ticket. The editing of vulnerabilities will be implemented in #96 .

**Comment by stevespringett** [comment]
Docs: https://docs.dependencytrack.org/usage/private-vulln-repo/
