### ISSUE TITLE
Allow Hierarchical Library/Application model

### ISSUE THREAD

**Issue by wjase** [stevespringett/dependency-track#29]
Where I work we maintain both applications and libraries with which we wish to maintain info on CVE's. At the moment DT has two hard and fast categories of things: libraries and applications. I'd like to see these two concepts harmonised into a tree of artifacts (not unlike maven's model of the world). That way I can get reports on vulerabilities on libraries, applications or even subsystems comprising several applications.
What are currently classed as 'Applications' in DT would simply become "artifacts of interest" which could then be reported upon. What constitutes an artifact of interest could either be flagged or rule-based. ie I'm interested in reported on any com.mycompany artifact.
This would allow more complicated suites or hardware/software combinations to be more intuitively managed

**Comment by stevespringett** [comment]
So if I understand correctly, you'd leave the components functionality in place but the grouping of those components (library in the data model) you'd prefer to have an unrestricted hierarchical relationship instead of a top-level application with a flat component structure?

If this were implemented it would allow an org to use DT in it's current manner (flat relationship) which would allow for an automated upgrade path, as well as more complicated parent-child tracking.

Do you have a vision for the UI? I've always found that web-based hierarchies typically have a lot of usability issues. I would want to stay away from a treeview for example, they're complicated to implement correctly and they're not designed for mobile use.

**Comment by stevespringett** [comment]
This feature is partially complete in 3.0 31d92630f313f714d46dc1cd99f18e4b3b3e53ff. The concept of 'Application' has changed to 'Project'. A project contains a hierarchy of components. When importing a DC scan, it will be flat. But the object model supports this now. The UI will have to take this into consideration once I start writing it.

**Comment by stevespringett** [comment]
Closing issue. Work is partially complete - see https://github.com/stevespringett/dependency-track/commit/31d92630f313f714d46dc1cd99f18e4b3b3e53ff . UI support for parent/child projects and components will be in a future release. Refer to #84
