### ISSUE TITLE
Components page doesnt work

### ISSUE THREAD

**Issue by javabeanz** [stevespringett/dependency-track#37]
I started dtrack with mvn clean package and then java -jar dtrack.war and was able to create an application with version. If I press the Components link, the page says Generic Error Message. the log shows :

javax.el.PropertyNotFoundException: The class 'java.lang.String' does not have t
he property 'licensename'.
        at javax.el.BeanELResolver.getBeanProperty(BeanELResolver.java:730) ~[ja

**Comment by nerdlife-zz** [comment]
Same problem here!

**Comment by joshijimit** [comment]
Same problem here!!

**Comment by stevespringett** [comment]
The trunk is not stable. Please download and use the released 1.0.0 version.

**Comment by javabeanz** [comment]
but build passing, but not stable, not even a deployment . what a disapointment

**Comment by stevespringett** [comment]
yeah, that's what happens when a project goes under major refactoring

**Comment by javabeanz** [comment]
it's great to have refactorings, maybe you could use a git branch for those

**Comment by stevespringett** [comment]
FYI, I have branched the project to make the source tree more clear.

- The only stable version (which can also be downloaded in a ready-to-deploy war) is 1.0.x.
- The master and 1.0-stable branches are in sync and should provide an easy way to compile your own war resulting in a working application.
- The 2.0-dev-springboot branch is unstable and has many issues. I do not intend to ever release this version. Just too many issues overall. This work was previously performed in the master branch but has since been reverted and separated to its own branch.
- All new development is being done in the 3.0-dev branch and is a complete rewrite of Dependency-Track from the ground up using modern technologies and an API-first design. It also doesn't rely on Spring.
