### ISSUE TITLE
Vendor list is empty when adding a component

### ISSUE THREAD

**Issue by KonstantinShemyak** [stevespringett/dependency-track#41]
When I attempt to add new component, I see no vendors in the dropdown vendor list. I can add my "own vendor" ("test-vendor" in the screenshot).

![dtrack](https://cloud.githubusercontent.com/assets/3096603/19958358/4b7afc98-a1a7-11e6-9501-cbc1c2f5882e.png)

`appHome/log/dependency-track.log` contains no errors. All NIST CVE files are successfully downloaded.

**Comment by stevespringett** [comment]
Works as designed. Dependency-Track is an asset management system for components and their relationships. The dropdown will list all previously entered vendors, or allow you to create your own simply by typing.

Future versions (v3.0 onwards) work completely different. But for the current released versions, this is expected behavior.
