### ISSUE TITLE
How to auto populate database by owasp reports

### ISSUE THREAD

**Issue by jimjaeger** [stevespringett/dependency-track#64]
Hi,

in your presentation https://www.youtube.com/watch?v=3B3VKGwYS2A you  mentioned a feature to import existing owasp reports into the application. How can I do it?

**Comment by stevespringett** [comment]
That specific video was for v1.0. I possibly mentioned it in the video, however, due to technical design limitations, that (any many other) features were put on hold until Dependency-Track could be re-written from scratch. See https://groups.google.com/forum/#!topic/dependency-track/f882I55JzDI for the back story.

I think you'll be interested in Dependency-Track v3, currently in active development. It's not quite ready for daily use, nor is it feature complete, but I'm anticipating beta releases by end of Q3.

See https://www.youtube.com/watch?v=88YAlzuDH04 for an introduction on how the ecosystem works, including a demo of publishing Dependency-Check results to Dependency-Track using the Jenkins plugin.

The version of the Jenkins plugin that does this has already been released. It's been available since 2.0.0. If you do not use Jenkins, the Swagger definition will provide you all the necessary details.

**Comment by jimjaeger** [comment]
Hi Steve,

thanks for the explanation. 

I have an application that contains of more than 70 self-contained components in different programming languages and build scripts that are each packaged in their own docker container. I have to manage the used open source. The solution I installed in the build pipeline is to extract the service folder of the container and run the owasp dependency checker to generate a report for each components in the pipeline. As result I have a bunch of owasp reports, for each component+version and I would like manage it in an automated way and push it into a tools that show the used the opensource from the entire application.

If deptrackV3 can be used for such usecases, then yes I am very interested in.
