### ISSUE TITLE
Exception uploading results

### ISSUE THREAD

**Issue by adunkey** [stevespringett/dependency-track#73]
Hi,

I have dependency check 2.1.1 & dependency tracker v3 setup & have a jenkins job to scan the jars of webgoat. The job runs fine & at the end of the build I get this in console output:
[DependencyTrack] Publishing Dependency-Check results to Dependency-Track
[DependencyTrack] The scan was successfully published

Now it is the .html file from dependency check that I am trying to publish. Nothing shows up in tracker UI; in the dependency-track.log I see the following:

2017-10-06 06:08:50,207 [] ERROR [org.owasp.dependencytrack.tasks.ScanUploadProcessingTask] Error while processing scan result
2017-10-06 06:08:50,207 [] ERROR [org.owasp.dependencytrack.tasks.ScanUploadProcessingTask] javax.xml.bind.UnmarshalException
 - with linked exception:
[com.sun.istack.internal.SAXParseException2; lineNumber: 6; columnNumber: 7; unexpected element (uri:"", local:"html"). Expected elements are <{}analysis>,<{}dataSource>,<{}dependency>,<{}evidence>,<{}identifier>,<{}identifiers>,<{}projectInfo>,<{}reference>,<{}scanInfo>,<{}vulnerabilities>,<{}vulnerability>]

any ideas??

**Comment by adunkey** [comment]
my fault; uploading the xml fixed that issue.

**Comment by adunkey** [comment]
![dtrackresultscomponentview](https://user-images.githubusercontent.com/4255262/31278343-7afe11cc-aa9c-11e7-8bbd-4ee5986dd39b.PNG)

I can't see any vulnerabilities though

**Comment by stevespringett** [comment]
Please update the checkout as this is outdated code. The dev-3.0 branch should be updated nearly every day since it's not stable and constantly changing. It should look like this:
<img width="1599" alt="screen shot 2017-10-06 at 10 24 51 am" src="https://user-images.githubusercontent.com/3878933/31285421-dbd77e8c-aa80-11e7-9a8d-965fcc838446.png">

The colored bar will indicate the number of critical, high, medium, and low severity vulnerabilities by the color used, or blue for none.
