### ISSUE TITLE
Update to SPDX 3.1

### ISSUE THREAD

**Issue by stevespringett** [stevespringett/dependency-track#87]
Work on SPDX 3.1 is in progress and will be released prior to Dependency-Track v3.0.

**Comment by stevespringett** [comment]
CycloneDX/specification#3

**Comment by adunkey** [comment]
getting this build error, using maven 3.5.0 & Java 1.8

[INFO] Running org.owasp.dependencytrack.parser.cyclonedx.CycloneDxParserTest
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 33.147 s <<< FAILURE! - in org.owasp.depend
encytrack.parser.cyclonedx.CycloneDxParserTest
[ERROR] testValidBom(org.owasp.dependencytrack.parser.cyclonedx.CycloneDxParserTest)  Time elapsed: 32.573 s  <<< E
RROR!
org.owasp.dependencytrack.exception.ParseException: org.xml.sax.SAXParseException; schema_reference.4: Failed to re
ad schema document 'http://cyclonedx.org/schema/bom/1.0', because 1) could not find the document; 2) the document c
ould not be read; 3) the root element of the document is not <xsd:schema>.
        at org.owasp.dependencytrack.parser.cyclonedx.CycloneDxParserTest.testValidBom(CycloneDxParserTest.java:45)

Caused by: org.xml.sax.SAXParseException: schema_reference.4: Failed to read schema document 'http://cyclonedx.org/
schema/bom/1.0', because 1) could not find the document; 2) the document could not be read; 3) the root element of
the document is not <xsd:schema>.
        at org.owasp.dependencytrack.parser.cyclonedx.CycloneDxParserTest.testValidBom(CycloneDxParserTest.java:45)

Caused by: java.net.ConnectException: Connection timed out: connect
        at org.owasp.dependencytrack.parser.cyclonedx.CycloneDxParserTest.testValidBom(CycloneDxParserTest.java:45)


[INFO] Running org.owasp.dependencytrack.parser.dependencycheck.DependencyCheckParserTest
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 47.822 s - in org.owasp.dependencytrack.pars
er.dependencycheck.DependencyCheckParserTest
[INFO] Running org.owasp.dependencytrack.parser.spdx.SpdxDocumentParserTest
[INFO] Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 150.277 s - in org.owasp.dependencytrack.par
ser.spdx.SpdxDocumentParserTest
[INFO]
[INFO] Results:
[INFO]
[ERROR] Errors:
[ERROR]   CycloneDxParserTest.testValidBom:45 ╗ Parse org.xml.sax.SAXParseException; sch...
[INFO]
[ERROR] Tests run: 8, Failures: 0, Errors: 1, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 06:57 min
[INFO] Finished at: 2018-01-18T09:47:13Z
[INFO] Final Memory: 42M/159M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.20.1:test (default-test) on project
 dependency-track: There are test failures.
[ERROR]

**Comment by adunkey** [comment]
build now works after latest commit

**Comment by stevespringett** [comment]
SPDX 3.1 is nearing release with several changes already merged in.

**Comment by stevespringett** [comment]
Waiting for the SPDX team to update the master license list. This was scheduled to be complete by February 15th. It has been delayed for unknown reasons. Putting this ticket on hold until 3.1 is released.

**Comment by stevespringett** [comment]
https://github.com/spdx/license-list-XML/milestone/3

**Comment by stevespringett** [comment]
The SPDX 3.1 release date has been pushed back. As a result, v3.1 may not make it into DTv3.

Note from SPDX project: 

> changes to be included for 3.1 release of the license list Update 2018-03-13: Marked target release > date 3/31/2018 per agreement on past several SPDX legal calls
